services: 
  movie.search_filter: 
    parent: 'api_platform.doctrine.orm.search_filter'
    arguments: [ { id: 'exact', title: 'partial', description: 'partial', category: 'exact' } ]
    tags: ['api_platform.filter']


# exact = where = id
# start = where field like "%value"
# end = where field like "value%"
# partial = where field like "%value%"
# word_start = "Value"